name: llscheck

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
    - main
  push:
    branches:
      - main

jobs:
  llscheck:
    runs-on: ubuntu-latest
    name: llscheck

    steps:
    - uses: actions/checkout@master

    - uses: rhysd/action-setup-vim@v1
      # NOTE: We need Neovim installed in order to expose the $VIMRUNTIME
      # environment variable
      with:
        neovim: true
        version: stable

    - uses: leafo/gh-actions-lua@v11
      with:
        # Neovim is compiled with LuaJIT so we might as well match. But it
        # doesn't look like we can match it exactly.
        #
        # Reference:
        #    https://github.com/leafo/gh-actions-lua/issues/49#issuecomment-2295071198
        #
        luaVersion: "luajit-openresty"

    - name: Install lua-language-server
      uses: jdx/mise-action@v2
      with:
        tool_versions: |
          lua-language-server latest

    - name: Install LuaRocks
      # TODO: Replace with https://github.com/luarocks/gh-actions-luarocks after v6+
      uses: ColinKennedy/gh-actions-luarocks@v1.0.0

    - name: Clone dependencies - luarocks-tag-release
      uses: actions/checkout@v5
      with:
        repository: "nvim-neorocks/luarocks-tag-release"
        path: ".dependencies/luarocks-rockspec-expander"

    - name: Print LuaRocks Versions
      run: |
        luarocks --version

    - name: Install llscheck
      run: |
        luarocks install llscheck

    - name: Print lua-language-server Version
      run: |
        lua-language-server --version

    - name: Test
      run: |
        make llscheck
